#!/usr/bin/env node
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function read(path) {
  return readFileSync(path, "utf8");
}

const panel = read("apps/app/src/react-app/domains/wallet/pages/BittensorPanel.tsx");
const surface = read("apps/app/src/react-app/domains/session/surface/session-surface.tsx");
const sharedCardRenderer = read("apps/app/src/react-app/domains/session/surface/message-list.tsx");
const rootPackage = JSON.parse(read("package.json"));

assert.equal(
  rootPackage.scripts?.["test:customer-readiness-ui"],
  "node scripts/customer-readiness-ui.test.mjs",
  "package.json should expose the customer readiness UI gate",
);

for (const phrase of [
  "Demo",
  "Monday beta launch checklist",
  "Run this launch-room checklist before each Monday beta customer call.",
  "App opens with first-class desks",
  "Crypto safety smoke is green",
  "Mac tester build and doctor pass",
  "Longevity workflow remains safe",
  "Copy launch check",
  "Monday beta promise",
  "VENUE_DESKS",
  "Start with your TAO, then choose what to do next.",
  "Preview Hyperliquid trades with the Hyperliquid Agent, with execution off.",
  "Analyze prediction markets and preview safely.",
  "BTC orderbook",
  "Find markets",
  "Exchange preview controls",
  "Market preview controls",
  "Readiness",
  "Ask Agent ->",
  "Evidence",
  "Safety",
  "/api/crypto/readiness",
  "/api/crypto/market-execution-readiness",
  "/api/crypto/market-execution-chain",
  "/api/crypto/market-sdk-validation",
  "MarketExecutionChainGuide",
  "loadMarketExecutionChain",
  "loadMarketSdkValidation",
  "marketExecutionChain",
  "marketSdkValidation",
  "All-protocol smoke",
  "Blocker:",
  "Next:",
  "Protocol Agent",
  "Market Agent",
  "crypto-readiness-panel",
  "market-execution-readiness-panel",
  "Do not ask for private keys, API secrets, raw signatures, signed payloads, or wallet exports.",
  "Protocol readiness is green for Bittensor, Hyperliquid, and Polymarket read/preview demo flows.",
  "matterhorn-work crypto readiness --json",
  "matterhorn-work crypto execution-readiness --json",
  "matterhorn-work crypto execution-chain --json",
  "pnpm test:market-sign-artifact-routes",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/readiness",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/market-execution-readiness",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/market-execution-chain",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/market-sdk-validation",
  "Authorization: Bearer $MATTERHORN_WORK_TOKEN",
  "pnpm smoke:customer-ready-crypto",
  "matterhorn-work crypto live-public-qa --output-dir /tmp/matterhorn-live-public-qa --fixture --strict --json",
  "Live public QA",
  "matterhorn-work crypto customer-packet",
  "matterhorn-work crypto evidence-verify",
  "Bittensor discovery",
  "TAO wallet",
  "Hyperliquid read",
  "Polymarket compliance",
  "Signer preview",
  "Can Matterhorn submit Hyperliquid and Polymarket orders yet?",
  "Preview Only",
  "Can submit: No",
  "Live submission: Off",
  "Execution readiness",
  "Ready for live submission",
  "Hyperliquid submit",
  "Polymarket submit",
  "Execution CLI",
  "Execution API",
  "This is a readiness contract, not execution permission.",
  "live submit routes until a separate security review",
  "Execution chain",
  "Testnet-only path: preview",
  "external-signer request",
  "redacted artifact validation",
  "public receipt import",
  "hash-bound",
  "Preview / handoff",
  "External-signer request",
  "Validate artifact",
  "Receipt import",
  "Route contract",
  "Chain CLI",
  "Chain API",
  "Stages",
  "matterhorn-work hyperliquid sign-request BTC",
  "matterhorn-work polymarket sign-request <testnet-market-id>",
  "testnet_external_signer",
  "matterhorn-work hyperliquid validate-artifact",
  "matterhorn-work polymarket validate-artifact",
  "matterhorn-work hyperliquid receipt",
  "matterhorn-work polymarket receipt",
  "SDK validation",
  "Official SDK validation is public/redacted evidence only.",
  "operator-owned testnet mode validates Hyperliquid testnet and Polygon Amoy artifacts",
  "matterhorn-work crypto sdk-doctor --strict --json",
  "matterhorn-work crypto sdk-validate-public",
  "--mode fixture",
  "--mode operator_owned_testnet",
  "--hyperliquid-network hyperliquid-testnet",
  "--polymarket-network polygon-amoy",
  "--polymarket-chain-id 80002",
  "matterhorn-work crypto sdk-loop",
  "SDK API",
  "Secrets accepted",
  "Private SDK run",
  "Explain official SDK validation for Hyperliquid and Polymarket.",
  "SDK doctor",
  "Fixture validate",
  "Testnet validate",
  "SDK loop",
  "Safe execution chain",
  "Confirm that Matterhorn rejects raw signatures, signed payloads, API secrets, private keys, hash mismatches, and any live submission request.",
  "reject raw signatures, signed payloads, secrets, and hash mismatches.",
  "Hyperliquid watch",
  "Polymarket watch",
  "Market watches",
  "Hyperliquid and Polymarket watches are read-only alert plans.",
  "watch_alert cards",
  "Funding, price/orderbook, position margin, open orders, and market availability.",
  "Market status, odds/liquidity movement, compliance block state, and public receipt/status changes.",
  "matterhorn-work hyperliquid watch create",
  "--kind funding_rate",
  "matterhorn-work hyperliquid watch check --json",
  "matterhorn-work hyperliquid watch digest --json",
  "matterhorn-work hyperliquid watch act",
  "<public-hyperliquid-watch.json>",
  "matterhorn-work polymarket watch create",
  "<public-market-id>",
  "matterhorn-work polymarket watch check --json",
  "matterhorn-work polymarket watch digest --json",
  "matterhorn-work polymarket watch act",
  "<public-polymarket-watch.json>",
  "Create HL watch",
  "Check HL watches",
  "Digest HL watches",
  "Act HL alert",
  "Create PM watch",
  "Check PM watches",
  "Digest PM watches",
  "Act PM alert",
  "review-only alert actions",
  "no orders are signed, submitted, or auto-executed",
  "Matterhorn prepares safe previews; your wallet/client decides whether anything is signed externally.",
  "External signer required",
  "Read/preview-only",
  "No market submit",
  "Protocol Agent",
  "Market Agent",
  "no seed phrases, private keys, API secrets, raw signatures, signed payloads, wallet exports, custody, or live Hyperliquid/Polymarket submission",
]) {
  assert.ok(panel.includes(phrase), `Bittensor panel should include customer demo checklist text: ${phrase}`);
}

for (const forbidden of [
  "/api/hyperliquid/orders/submit",
  "/api/polymarket/orders/submit",
  "privateKey:",
  "apiSecret:",
  "rawSignature:",
  "signedPayload:",
]) {
  assert.equal(panel.includes(forbidden), false, `customer UI must not include forbidden execution/secret surface ${forbidden}`);
}

assert.ok(panel.includes("matterhorn:crypto-chat-handoff"), "demo tasks should use the generic crypto handoff event");
assert.ok(surface.includes("matterhorn:crypto-chat-handoff"), "session surface should listen for the generic crypto handoff event");
assert.ok(surface.includes("task ready"), "session notice should distinguish protocol agent tasks from Bittensor-only tasks");
assert.ok(surface.includes("crypto.chat_handoff.applied"), "generic crypto handoffs should have their own inspector event");
assert.ok(sharedCardRenderer.includes("matterhorn.crypto.shared-card.v1"), "transcript should render versioned shared crypto cards");

console.log("Customer readiness UI static check passed.");
