#!/usr/bin/env node
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function read(path) {
  return readFileSync(path, "utf8");
}

const panel = read("apps/app/src/react-app/domains/wallet/pages/BittensorPanel.tsx");
const surface = read("apps/app/src/react-app/domains/session/surface/session-surface.tsx");
const sharedCardRenderer = read("apps/app/src/react-app/domains/session/surface/message-list.tsx");
const rootPackage = JSON.parse(read("package.json"));

assert.equal(
  rootPackage.scripts?.["test:customer-readiness-ui"],
  "node scripts/customer-readiness-ui.test.mjs",
  "package.json should expose the customer readiness UI gate",
);

for (const phrase of [
  "Demo",
  "Release test checklist",
  "Run this launch-room checklist before customer use.",
  "App opens with first-class desks",
  "Crypto safety smoke is green",
  "Mac tester build and doctor pass",
  "Longevity workflow remains safe",
  "Copy launch check",
  "Release boundary",
  "VENUE_DESKS",
  "Start with your TAO, then choose what to do next.",
  "Research and execute Hyperliquid perpetual orders with wallet review.",
  "Analyze prediction markets and trade with wallet approval.",
  "BTC orderbook",
  "Find markets",
  "Exchange safeguards",
  "Market preview controls",
  "Readiness",
  "Ask Agent ->",
  "Evidence",
  "Safety",
  "/api/crypto/readiness",
  "/api/crypto/market-execution-readiness",
  "/api/crypto/market-execution-chain",
  "/api/crypto/market-sdk-validation",
  "MarketExecutionChainGuide",
  "loadMarketExecutionChain",
  "loadMarketSdkValidation",
  "marketExecutionChain",
  "marketSdkValidation",
  "All-protocol smoke",
  "Blocker:",
  "Next:",
  "Protocol Agent",
  "Market Agent",
  "crypto-readiness-panel",
  "market-execution-readiness-panel",
  "Do not ask for private keys, API secrets, raw signatures, signed payloads, or wallet exports.",
  "Protocol readiness is green within each desk boundary",
  "matterhorn-work crypto readiness --json",
  "matterhorn-work crypto execution-readiness --json",
  "matterhorn-work crypto execution-chain --json",
  "pnpm test:market-sign-artifact-routes",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/readiness",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/market-execution-readiness",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/market-execution-chain",
  "$MATTERHORN_WORK_SERVER_URL/api/crypto/market-sdk-validation",
  "Authorization: Bearer $MATTERHORN_WORK_TOKEN",
  "pnpm smoke:customer-ready-crypto",
  "matterhorn-work crypto live-public-qa --output-dir /tmp/matterhorn-live-public-qa --fixture --strict --json",
  "Live public QA",
  "matterhorn-work crypto customer-packet",
  "matterhorn-work crypto evidence-verify",
  "Bittensor discovery",
  "TAO wallet",
  "Hyperliquid read",
  "Polymarket compliance",
  "Signer preview",
  "Review the current Hyperliquid and Polymarket execution contract.",
  "Agents prepare drafts only.",
  "Can submit: No",
  "Live submission: Off",
  "Execution readiness",
  "Ready for live submission",
  "Hyperliquid orders can submit only after you review the network, asset, side, size, price or slippage boundary, and reduce-only state, then sign the exact short-lived intent in your connected wallet.",
  "Eligible Polymarket EOA buy, sell, and cancel actions can submit only after compliance passes and you authorize the exact action in a connected Polygon wallet.",
  "Execution CLI",
  "Execution API",
  "Every order is hash-bound to the reviewed terms, expires quickly, can submit once, and must be signed by the connected wallet.",
  "Agents and watches cannot submit; each supported action requires a separate, short-lived wallet approval.",
  "Execution chain",
  "Testnet-only validation path: preview",
  "operator-owned wallet check",
  "redacted artifact validation",
  "public receipt import",
  "hash-bound",
  "Preview / handoff",
  "Operator wallet check",
  "Validate artifact",
  "Receipt import",
  "Route contract",
  "Chain CLI",
  "Chain API",
  "Stages",
  "matterhorn-work hyperliquid sign-request BTC",
  "matterhorn-work polymarket sign-request <testnet-market-id>",
  "testnet_external_signer",
  "matterhorn-work hyperliquid validate-artifact",
  "matterhorn-work polymarket validate-artifact",
  "matterhorn-work hyperliquid receipt",
  "matterhorn-work polymarket receipt",
  "SDK validation",
  "Official SDK validation is public/redacted evidence only.",
  "operator-owned testnet mode validates Hyperliquid testnet and Polygon Amoy artifacts",
  "matterhorn-work crypto sdk-doctor --strict --json",
  "matterhorn-work crypto sdk-validate-public",
  "--mode fixture",
  "--mode operator_owned_testnet",
  "--hyperliquid-network hyperliquid-testnet",
  "--polymarket-network polygon-amoy",
  "--polymarket-chain-id 80002",
  "matterhorn-work crypto sdk-loop",
  "SDK API",
  "Secrets accepted",
  "Private SDK run",
  "Explain official SDK validation for Hyperliquid and Polymarket.",
  "SDK doctor",
  "Fixture validate",
  "Testnet validate",
  "SDK loop",
  "Safe execution chain",
  "Confirm that the agent artifact cannot submit, reviewed terms cannot be changed after authorization, and Matterhorn rejects secrets, arbitrary signed payloads, hash mismatches, and unattended submission.",
  "reject raw signatures, signed payloads, secrets, and hash mismatches.",
  "Hyperliquid watch",
  "Polymarket watch",
  "Market watches",
  "Hyperliquid and Polymarket watches are read-only alert plans.",
  "watch_alert cards",
  "Funding, price/orderbook, position margin, open orders, and market availability.",
  "Market status, odds/liquidity movement, compliance block state, and public receipt/status changes.",
  "matterhorn-work hyperliquid watch create",
  "--kind funding_rate",
  "matterhorn-work hyperliquid watch check --json",
  "matterhorn-work hyperliquid watch digest --json",
  "matterhorn-work hyperliquid watch act",
  "<public-hyperliquid-watch.json>",
  "matterhorn-work polymarket watch create",
  "<public-market-id>",
  "matterhorn-work polymarket watch check --json",
  "matterhorn-work polymarket watch digest --json",
  "matterhorn-work polymarket watch act",
  "<public-polymarket-watch.json>",
  "Copy watch setup command",
  "Check HL watches",
  "Copy watch digest command",
  "Act HL alert",
  "Check PM watches",
  "Act PM alert",
  "Developer tools",
  "Copy CLI commands. Nothing runs automatically.",
  "Copy signer examples",
  "Copy SDK check command",
  "review-only alert actions",
  "no orders are signed, submitted, or auto-executed",
  "Every supported transfer or trade uses a separate reviewed ticket and connected-wallet approval.",
  "Hyperliquid and eligible Polymarket buy, sell, and cancel actions require exact review and a fresh wallet approval.",
  "Bittensor actions require connected-wallet approval",
  "Automatic execution off",
  "Polymarket compliance gate",
  "Wallet approval per action",
  "Protocol Agent",
  "Market Agent",
  "No seed phrases, private keys, API secrets, raw signatures, arbitrary signed payloads, wallet exports, custody, or automatic execution.",
]) {
  assert.ok(panel.includes(phrase), `Bittensor panel should include customer demo checklist text: ${phrase}`);
}

for (const forbidden of [
  "/api/polymarket/orders/submit",
  "privateKey:",
  "apiSecret:",
  "rawSignature:",
  "signedPayload:",
]) {
  assert.equal(panel.includes(forbidden), false, `customer UI must not include forbidden execution/secret surface ${forbidden}`);
}

assert.ok(panel.includes("/api/hyperliquid/actions/execution-intent"), "customer UI must prepare an exact Hyperliquid action intent");
assert.ok(panel.includes("/api/hyperliquid/orders/submit"), "customer UI must expose the wallet-approved Hyperliquid submit route");

assert.ok(panel.includes("matterhorn:crypto-chat-handoff"), "demo tasks should use the generic crypto handoff event");
assert.ok(surface.includes("matterhorn:crypto-chat-handoff"), "session surface should listen for the generic crypto handoff event");
assert.ok(surface.includes("task ready"), "session notice should distinguish protocol agent tasks from Bittensor-only tasks");
assert.ok(surface.includes("crypto.chat_handoff.applied"), "generic crypto handoffs should have their own inspector event");
assert.ok(sharedCardRenderer.includes("matterhorn.crypto.shared-card.v1"), "transcript should render versioned shared crypto cards");

console.log("Customer readiness UI static check passed.");
