// Authored public guidance only. Never import account, runtime or vault data here.
export const PUBLIC_ORIGIN = "https://desks.matterhorn.so";
export const CONTENT_DATE = "2026-10-02";
export const REPOSITORY = "https://github.com/matterhornso/matterhorn-work";

export const publicGuides = [
  {
    slug: "", label: "Start here", title: "An AI workspace for crypto research",
    description: "Understand Matterhorn Desks: choose your model, open a focused crypto desk, and check the evidence behind an answer before deciding what to do.",
    answer: "Matterhorn Desks brings model choice, protocol-specific tools and research conversations into one workspace. Its five primary desks are Private AI, Bittensor, Hyperliquid, Polymarket and Sui. Choose the desk that matches your question; treat a model's explanation and a verified tool result as different kinds of evidence.",
    sections: [
      { title: "What does cowork for crypto mean?", paragraphs: ["Here it means doing a research task with an AI assistant and the appropriate crypto tools: define the question, obtain available evidence, review the answer and keep useful context. It does not mean giving an agent unrestricted control over a wallet. Matterhorn is an independent product; this description does not imply affiliation with Anthropic or Claude Cowork.", "A general chatbot can explain concepts. A desk adds task-specific context and supported tools. A wallet signs approved transactions. These roles are separate: an articulate answer is not proof of a live-chain read, and a connected wallet is not proof that a desk's agent is ready."] },
      { title: "Choose the desk for the question", links: [
        ["/learn/private-ai", "Private AI: general research, model choice and data boundaries"],
        ["/learn/bittensor", "Bittensor: public subnet, validator and wallet research"],
        ["/learn/hyperliquid", "Hyperliquid: order books, funding and account exposure"],
        ["/learn/polymarket", "Polymarket: exact markets, outcomes and liquidity"],
        ["/learn/sui", "Sui: public objects and addresses on an explicit network"],
      ] },
      { title: "From a question to useful work", steps: ["Open the app and sign in through the normal account flow. Registration and recovery depend on deployment availability.", "Choose an available chat model and check the model shown before sending. Workspace defaults can apply when no model is selected.", "Open a desk and write your question, or edit a starter suggestion. Specify the network, market, subnet or public identifier when the task needs one.", "Review the completed response and its tool evidence. Resolve missing sources, stale data or unavailable services before relying on the conclusion." ] },
      { title: "What this beta does not promise", paragraphs: ["A guide describes an intended supported workflow, not the current health of every deployment. Models, tools and network services can be unavailable or rate-limited. Check the app's actual setup and error state. Do not infer readiness from a desk icon.", "Research is not personalized financial advice, a trading recommendation or a promise of returns. Never paste seed phrases, private keys or API secrets into a prompt. Financial actions, where explicitly enabled, require their own review and signing flow; reading this guide grants no permission to execute them."] },
      { title: "Inspect the product and its boundaries", links: [["/learn/check-an-ai-crypto-answer", "How to check an AI crypto-research answer"], ["/security", "Security model and vulnerability reporting"], ["/privacy", "Data and provider privacy"], [REPOSITORY, "Matterhorn source repository"]] },
    ],
  },
  {
    slug: "private-ai", label: "Private AI", title: "Private AI: choose a model and control your context",
    description: "Start general AI work in Matterhorn, understand which provider processes a prompt, and keep model choice, saved memory and optional Jev classification separate.",
    answer: "Private AI is Matterhorn's general-purpose desk. Use it for explanation, drafting and tasks that do not need a specific protocol desk. The name does not guarantee on-device processing: where a prompt goes depends on the selected model, provider policy and deployment configuration.",
    sections: [
      { title: "Start with a bounded question", paragraphs: ["Select an available model in the app, open Private AI and start with a harmless prompt. Check the displayed provider and privacy details before sending sensitive content. A provider connection, policy approval and working runtime are prerequisites, not benefits implied by the desk name."], prompt: "Explain the difference between a wallet address and a private key in three short paragraphs. Do not request any credentials or inspect my workspace files." },
      { title: "Keep three kinds of context separate", items: ["Conversation context: the messages and permitted inputs used for the current task.", "Saved memory: user-controlled records whose availability and use depend on workspace configuration. Review provenance and sensitivity before confirming a memory.", "Optional Jev classification: a separate opt-in preprocessing service. If enabled, review its data-sharing terms; your selected model still answers the chat."] },
      { title: "Check the answer and the processing path", paragraphs: ["For a concept explanation, a completed selected-model response is the immediate outcome. If a task also requires files or external tools, inspect whether those operations actually occurred. Do not treat a confident summary as proof that a tool ran.", "Hosted storage, a local desktop workspace, provider-held copies, exports and backups are different locations with different lifecycles. Deleting a saved memory is not a promise to erase every conversation, export or provider copy. Read the deployment's privacy notice before choosing what to share."] },
      { title: "When the model is unavailable", paragraphs: ["If no models are listed, follow the app's owner setup or contact-owner guidance. If policy verification blocks sending, do not bypass it. A throttled or disconnected provider is not fixed by switching desks. Preserve your draft and use the available retry or reconnection path without repeatedly submitting the same request."] },
      { title: "Read before sharing sensitive context", links: [["/privacy", "Matterhorn privacy notice"], ["/security", "Matterhorn security model"], ["/learn/check-an-ai-crypto-answer", "Check an AI answer before relying on it"]] },
    ],
  },
  {
    slug: "bittensor", label: "Bittensor", title: "Research Bittensor subnets with an AI desk",
    description: "A read-only Bittensor research workflow: specify a subnet, request public-chain evidence, check units and freshness, and recognize missing live-service access.",
    answer: "Use the Bittensor desk to frame questions about public subnet, validator or wallet activity. Begin with an explicit subnet or public address and ask for the network, observation time and units. A useful result separates what was retrieved from what the model inferred.",
    sections: [
      { title: "Provide the question, not a secret", paragraphs: ["A subnet identifier narrows the subject. A public SS58 address can identify a wallet for a read-only question. Neither requires a seed phrase or signing key. Avoid asking for the best subnet without defining the criteria and the period you want examined."], prompt: "Research Bittensor subnet [subnet ID] on the intended network using available public reads. State the source, observation time, units and any missing fields. Explain what the data can and cannot tell us. Do not prepare or submit a transaction." },
      { title: "Read the evidence before the conclusion", items: ["Confirm the subnet identifier and network match your request; similarly named subnets are not substitutes.", "Check whether the result came from a live service, a cached observation or model knowledge. Ask for the observation time or block reference when available.", "Keep TAO amounts, subnet-specific amounts, proportions and time periods distinct. Do not compare numbers whose units or basis are missing.", "Separate public observations from predictions about future rewards, validator quality or token value."] },
      { title: "Recognize an unavailable chain read", paragraphs: ["An agent-unavailable message, an unconfigured chain service or a failed tool call means the live-read part of the task has not completed. A model can still describe Bittensor generally, but that is not a replacement for current subnet evidence. Follow setup or retry guidance rather than treating a partial explanation as a successful read.", "Validator comparisons depend on the criteria you choose and the evidence returned. This guide does not endorse a validator, predict returns or authorize staking. Wallet-review features, if enabled for a release, remain separate from research."] },
      { title: "Go to the source", paragraphs: ["Bittensor's documentation explains its network, subnets and tooling. Use it to verify terminology and inspect assumptions behind a research question; it does not certify Matterhorn's current runtime availability."], links: [["https://www.bittensor.com/docs", "Official Bittensor documentation"], ["/learn/check-an-ai-crypto-answer", "Evidence checklist for AI crypto research"]] },
    ],
  },
  {
    slug: "hyperliquid", label: "Hyperliquid", title: "Inspect Hyperliquid markets without placing a trade",
    description: "Use the Hyperliquid desk for read-only market research: identify the instrument, examine order-book and funding evidence, and keep analysis separate from execution.",
    answer: "The Hyperliquid desk is a starting point for questions about market structure, funding and public account exposure. Specify the market and whether you mean spot or perpetuals. Review the returned snapshot and its limitations before accepting the model's explanation.",
    sections: [
      { title: "Ask for a particular market", paragraphs: ["Symbols alone can be ambiguous across market types or venues. Provide the full instrument context. If researching a public account, use the actual account address for the question; an agent wallet address may not describe the same exposure."], prompt: "Inspect the BTC perpetual market on Hyperliquid using available public reads. Summarize spread, order-book depth and funding, with source and observation time. Preserve all stale-data or incomplete-data warnings. Research only; do not place, cancel or prepare an order." },
      { title: "What to verify in the result", items: ["Instrument and market type: confirm the response did not silently switch to spot or another asset.", "Snapshot timing: an order book changes quickly; a point-in-time read is not continuous monitoring.", "Spread and depth: check the levels or range used in the summary. Available depth is not a guarantee of execution price.", "Funding: retain the reported interval and units. Do not turn a single observation into an unexplained annualized return.", "Warnings: if a tool reports stale or missing data, the final answer must not say that there are no warnings."] },
      { title: "Account research is not wallet access", paragraphs: ["A read-only exposure question should not need a private key or permission to trade. Empty account data can result from a wrong identifier; it is not sufficient proof of zero risk. Confirm which account was queried and what the endpoint returned.", "If a tool is unavailable, preserve the request and use the app's setup or retry guidance. Never convert research into order submission to make the workflow appear successful. A review screen or model suggestion is not permission to sign."] },
      { title: "Verify endpoint semantics", links: [["https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint", "Hyperliquid public information endpoint documentation"], ["/learn/check-an-ai-crypto-answer", "Check sources, freshness and conclusions"]] },
    ],
  },
  {
    slug: "polymarket", label: "Polymarket", title: "Research a Polymarket market with verifiable context",
    description: "Identify an exact Polymarket market, inspect outcomes and liquidity, and distinguish retrieved market data from an AI prediction or a trade recommendation.",
    answer: "Use the Polymarket desk to research a specific market and its available public data. Choose the exact market rather than relying on a broad headline. A useful answer identifies the market, outcome, observation time and source, and explains gaps without inventing a substitute.",
    sections: [
      { title: "Begin with an exact market", paragraphs: ["A headline may describe several markets, dates or outcomes. Supply the market URL or identifier you intend to research, then verify that the returned question matches it. If the app asks you to disambiguate, choose deliberately instead of accepting a similarly named market."], prompt: "Research this exact Polymarket market: [public market URL or identifier]. Summarize its question, outcomes and available price/liquidity data. Cite the source and observation time, distinguish missing data, and do not recommend or submit a trade." },
      { title: "Inspect the market, not just the summary", items: ["Identity: match the question, market identifier and relevant date to your request.", "Outcome: identify which outcome a quoted number refers to. Do not confuse an outcome token, a market and a broader event.", "Rules: read the market's own resolution conditions. A short model summary is not a replacement for the source terms.", "Liquidity and price: check the retrieved fields and observation time; a displayed number does not guarantee a fill.", "Interpretation: market data and the model's prediction are different. Confidence in prose is not new evidence."] },
      { title: "Handle missing or stale results", paragraphs: ["If the exact market cannot be retrieved, stop the specific analysis and check the identifier or service status. A description of prediction markets generally is not a successful read of your selected market. Keep stale-data and partial-result warnings in any saved research note.", "This workflow is informational, not betting advice or a promise of outcome accuracy. Protocol access and eligibility can vary. Nothing in a read-only research answer grants account access or approval for a transaction."] },
      { title: "Check the primary documentation", links: [["https://docs.polymarket.com/", "Official Polymarket documentation"], ["/learn/check-an-ai-crypto-answer", "Check an AI research answer"]] },
    ],
  },
  {
    slug: "sui", label: "Sui", title: "Inspect Sui objects and addresses on the right network",
    description: "A read-only Sui workflow: provide a public identifier and network, inspect returned object or account data, and distinguish missing results from verified absence.",
    answer: "Use the Sui desk for public object or address research with an explicit network. An object identifier alone is not enough context for a reliable cross-network answer. Check that the tool actually queried the requested network and preserve its source and limitations.",
    sections: [
      { title: "Name the network and identifier", paragraphs: ["Specify mainnet, testnet or the configured network you intend to inspect, and state whether your identifier is an address, object or transaction digest. Do not infer an object's network from its appearance. Public reads should not require a wallet seed phrase."], prompt: "On Sui [network], inspect public object [object ID] using the available read tool. Explain the returned fields, source and observation time or checkpoint if available. If the object cannot be found, state the actual error and do not invent an owner or switch networks. Do not prepare or sign a transaction." },
      { title: "What a completed read should establish", items: ["The requested network and identifier were used; no silent fallback to another network.", "Returned fields are separated from inferred meaning. If an owner, version or type is absent, the answer should say so.", "A source and observation reference are included when the tool provides them. An unreported checkpoint should not be invented.", "Not-found, permission and transport failures are distinguished; a failed request is not proof that no object or balance exists."] },
      { title: "Keep object research separate from transfers", paragraphs: ["Sui uses an object-centric model; different objects and ownership arrangements have different meanings. Consult the official model documentation when interpreting an unfamiliar type. Do not assume that a model's explanation establishes transferability.", "A wallet-support badge describes an integration, not a successful agent or network read. If the agent or tool is unavailable, follow setup guidance and retain your draft. Any supported transfer-review path is a separate action with explicit terms and signing requirements."] },
      { title: "Read the protocol's model", links: [["https://docs.sui.io/develop/sui-architecture/object-model", "Sui object model documentation"], ["/learn/check-an-ai-crypto-answer", "Evidence checklist for crypto research"]] },
    ],
  },
  {
    slug: "check-an-ai-crypto-answer", label: "Check an answer", title: "How to check an AI crypto-research answer",
    description: "A practical checklist for crypto AI research: verify identity, tool evidence, freshness, units and uncertainty before saving a conclusion or taking action.",
    answer: "Check the underlying evidence before trusting an AI crypto-research answer. Confirm the entity and network, distinguish retrieved data from model inference, and retain observation times, units and warnings. A completed chat is not automatically a completed research task.",
    sections: [
      { title: "Five checks before you rely on a result", steps: ["Identity: does the answer refer to the exact subnet, instrument, market or object you requested, on the right network?", "Retrieval: did the required tool return a result, or did the model only give a general explanation? Open available tool details when the distinction is unclear.", "Time: is the observation current enough for your question? Separate current reads, cached records and historical knowledge; do not guess missing timestamps.", "Meaning: are units, intervals and denominators explicit? A percentage, token amount, price and annualized estimate are not interchangeable.", "Uncertainty: does the conclusion preserve the tool's errors, limitations and stale-data warnings? Ask for a correction when the summary contradicts the evidence."] },
      { title: "A prompt for a second pass", prompt: "Review your previous answer against the tool evidence already returned. List unsupported claims, missing source/time/unit fields and any warnings that were omitted. Do not repeat tools, take new actions or invent missing data; say what remains unverified." },
      { title: "When to stop instead of retry", paragraphs: ["Stop when the requested entity cannot be identified, an essential provider or agent is unavailable, or the data source cannot support the conclusion. Repeated sends can consume allowance without improving evidence. Use the app's supported retry or continuation action and check usage rather than assuming it is free.", "A request to revise prose must not become permission to run new wallet actions. Review any tool or transaction approval separately. Never paste a seed phrase, private key or API secret as a workaround for a failing research tool."] },
      { title: "Keep a useful research note", paragraphs: ["Record the question, public identifier, network, observation time, source, main finding and unresolved limitations. Save only what you intend to retain. Explicit saved memory, notes, chat history, exports and backups have different lifecycles; understand the workspace policy before storing sensitive context.", "This checklist helps assess evidence quality; it is not an audit, investment recommendation or guarantee of safety. Confirm consequential decisions independently."], links: [["/learn/bittensor", "Bittensor example"], ["/learn/hyperliquid", "Hyperliquid example"], ["/learn/polymarket", "Polymarket example"], ["/learn/sui", "Sui example"], ["/privacy", "Data and memory boundaries"]] },
    ],
  },
];

export function guidePath(guide) {
  return guide.slug ? `/learn/${guide.slug}` : "/learn";
}
